spring:
  application:
    name: metal-prices

custom:
  mail:
    sender: no-reply@b-l-s.click
    recipients: brano.beno@gmail.com,ivana.chvojkova@gmail.com
  metal:
    api:
      url: "https://metals-api.com/api"
      access-key: "m2cdomyl0maomym5m39xqpm42u0rjl67k47nok088xjix3686y7r65iv4j7l"
      symbols: "LME-ALU,LME-XCU,LME-LEAD"
      base: "EUR"
